version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback 
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      #add-on
      - run: npm test
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: 
          name: "Build docker image and push to docker hub"
          command: |
            if ["$CIRCLE_BRANCH" == "master"]; then
              cp Dockerfile.production Dockerfile
              docker build -t tayakorn/day3workshop:latest . #create repository on docker hub
              docker build -t tayakorn/day3workshop:${CIRCLE_SHA1} .  #build for unique
              docker push tayakorn/day3workshop:latest
              docker push tayakorn/day3workshop:${CIRCLE_SHA1}
            elif ["$CIRCLE_BRANCH" == "staging"]; then
              docker build -t tayakorn/day3workshop_staging:latest . #create repository on docker hub
              docker push tayakorn/day3workshop_staging:latest
            else
              echo "This is $CIRCLE_BRANCH"
      - run:
          name: "Call to rancher to deploy"
          command: |
              docker run --rm -it \
                -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
                -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
                -e CATTLE_URL="$CATTLE_URL" \
                etlweather/gaucho upgrade 1s16 \
                --imageUuid 'docker:tayakorn/day3workshop:latest' \
                --batch_size 5 --start_first \
                --auto_complete --timeout 600 
      - run: echo Done

